### ISSUE TITLE
get_xzy_randn_nl can be simplified

### ISSUE THREAD

**Issue by dirknbr** [romanpogodin/kernel-ci-testing#2]
get_xzy_randn_nl can pssoibly be simplifed as

```
def get_xzy_randn_nl(**)
  x, z, y = get_xzy_randn(**)
  x = x ** 2
  return x, z, y
```

**Comment by romanpogodin** [comment]
Agreed, thank you for pointing this out! I'll leave the code as it is for now since we're planning to make a more global update soon.
